### ISSUE TITLE
Version 1.0 milestones

### ISSUE THREAD

**Issue by margunwa123** [margunwa123/peer-assessment#2]
- [x] Add title on all pages
- [x] Add download data functionality (to CSV format) -> can choose per assessment / group
- [x] More file format when making the assessment (CSV for example)
- [x] Add help button (when clicked open modal) when making the assessment
- [x] Add user tutorial
- [x] User testing
- [x] Can edit group data when making the assessment
- [x] Integration with nimfinder so user does not have to input with name
- [x] Add manual data
- [x] Edit Assessment
- [x] Edit Filled Peer Assessment
- [x] Consult with Labpro
- [x] Add Readme
- [x] Add more mock data
- [x] Fix bug 1 orang doang yg bisa ngisi
- [x] Fix bug semua peer assessment keliatan di my created assessment
